apps/servicos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('listar/', views.listar_servicos, name='listar-servicos'),
    path('cadastro/', views.cadastro_servicos, name='cadastro-servicos'),
    path('editar/<int:id>', views.editar_servico, name='editar-servico'),
    path('apagar/<int:id>', views.apagar_servico, name='apagar-servico'),
]

petshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('cliente/', include('cliente.urls')),
    path('admin/', admin.site.urls),
    path('usuario/', include('usuario.urls')),
    path('pet/', include('pet.urls')),
    path('servicos/', include('servicos.urls')),
    
]

apps/servicos/models.py
from django.db import models

class Servico(models.Model):
    client = models.CharField(max_length=50, blank=True, default='')
    animal = models.CharField(max_length=50, blank=True, default='')

    TYPES = (
        ('banho', 'Banho'),
        ('tosa', 'Tosa'),
        ('vacina', 'Vacina')
    )

    PAYMENTS = (
        ('money', 'Dinheiro'),
        ('card', 'Cartão de crédito'),
        ('bank-transfer', 'Transferência bancária'),
        ('pix', 'Pix')
    )

    type = models.CharField(max_length=6, blank=True, choices=TYPES, default='')
    payment = models.CharField(max_length=50, blank=True, choices=PAYMENTS, default='')

    def __str__(self):
        return str(self.type)

apps/servicos/views.py
from pydoc import cli
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from servicos.models import Servico

@login_required(login_url='/usuario/login')
def listar_servicos(request):
	servicos = Servico.objects.all()

	context = {
		'servicos': servicos
	}

	return render(request, 'servicos/listar_servicos.html', context)

@login_required(login_url='/usuario/login')
def cadastro_servicos(request):
	if request.method == 'POST':
		client = request.POST['client']
		animal = request.POST['animal']
		type = request.POST['type']
		payment = request.POST['payment']

		try:
			servico = Servico()
			servico.client = client
			servico.animal = animal
			servico.type = type
			servico.payment = payment
			servico.save()
			messages.success(request, 'Cadastro realizado com sucesso!')
		except Exception:
			messages.error(request, 'Ocorreu algum erro ao cadastrar!')

		return redirect('/servicos/cadastro')

	return render(request, 'servicos/cadastro_servicos.html')

@login_required(login_url='/usuario/login')
def editar_servico(request, id):
	if request.method == 'POST':
		client = request.POST['client']
		animal = request.POST['animal']
		type = request.POST['type']
		payment = request.POST['payment']

		try:
			Servico.objects.filter(id=id).update(client=client, animal=animal, type=type, payment=payment)
			messages.success(request, 'Dados editados com sucesso!')
			return redirect('/servicos/listar')
		except Exception:
			messages.error(request, 'Ocorreu algum erro ao editar os dados!')

		return redirect('/servicos/listar')

	servico = Servico.objects.filter(id=id)[0]

	context = {
		'servico': servico
	}

	return render(request, 'servicos/editar_servico.html', context)

@login_required(login_url='/usuario/login')
def apagar_servico(request, id):
	try:
		Servico.objects.filter(id=id).delete()
		messages.success(request, 'Dados apagados com sucesso!')
	except Exception:
		messages.error(request, 'Ocorreu algum erro ao apagar os dados!')

	return redirect('/servicos/listar')

templates/servicos/cadastro_servicos.html
{% extends 'usuario/dashboard.html' %}
{% load static %}
{% block dash %}
<section #servico class="card_pet container">
    <div class="card sub_card_pet">
        <div class="card-header card__titulo">
            <h5>Cadastro de Serviços</h5>
        </div>
        <div class="card-body">
            <form action="{% url 'cadastro-servicos' %}" method="POST" class="row g-3" >
                {% csrf_token %}
                {% if messages %}
                    {% for message in messages %}
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                            <p style="color: red; margin-bottom: 0; margin-left: 8px;">
                                {{ message }}
                            </p>
                            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                            <p style="color: green; margin-bottom: 0; margin-left: 8px;">
                                {{ message }}
                            </p>
                        {% endif %}
                    {% endfor %}
                {% endif %}

                <div class="col-md-6">
                    <label for="client" class="form-label">Cliente</label>
                    <input type="text" class="form-control"  id="client" name="client" minlength="3" maxlength="50" required>
                </div>
                <div class="col-md-6">
                    <label for="animal" class="form-label">Animal</label>
                    <input type="text" class="form-control"  id="animal" name="animal" minlength="3" maxlength="50"
                    title="Informe um nome válido." required>
                </div>
                <div class="col-md-6">
                    <label for="type" class="form-label">Tipo de serviço</label>
                    <select class="form-select" name="type" required>
                        <option value="banho">Banho</option>
                        <option value="tosa">Tosa</option>
                        <option value="vacina">Vacina</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="payment" class="form-label">Forma de pagamento</label>
                    <select class="form-select" name="payment" required>
                        <option value="money">Dinheiro</option>
                        <option value="card">Cartão de crédito</option>
                        <option value="bank-transfer">Transferência bancária</option>
                        <option value="pix">Pix</option>
                    </select>
                </div>

                <div class="col-md-12 d-flex justify-content-between align-items-center mt-5">
                    <div>
                        <label class="form-label" for="date_cadastro">Data de Cadastro:</label>
                        <p>28/03/2022</p>
                    </div>

                    <div class="card_Pet_btn">
                        <button type="submit" class="btn card-btn-primary"><i class="fa-solid fa-floppy-disk"></i>
                            Cadastrar</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/servicos/editar_servico.html
{% extends 'usuario/dashboard.html' %}
{% load static %}
{% block dash %}
<section #servico class="container servico_form">
    <div class="tela">
        <form action="{% url 'editar-servico' servico.id %}" method="POST">
            {% csrf_token %}
            <table id="tab" cellspacing="2" cellpadding="2">
                <th colspan="3">
                    <h3>Serviços</h3>
                </th>	
                
                <tr>
                    <td>Cliente</td>
                    <td><input type="text" name="client" value="{{ servico.client }}" size="60" minlength="3" maxlength="50" required></td>
                </tr>
                <tr>
                    <td>Animal</td>
                    <td><input type="text" name="animal" value="{{ servico.animal }}" size="60" minlength="3" maxlength="50" required></td>
                </tr>
                <tr>
                    <td>Tipo de serviço</td>
                    <td>
                        <select class="form-select" name="type" required>
                            <option value="banho" {% if servico.type == 'banho' %}selected{% endif %}>Banho</option>
                            <option value="tosa" {% if servico.type == 'tosa' %}selected{% endif %}>Tosa</option>
                            <option value="vacina" {% if servico.type == 'vacina' %}selected{% endif %}>Vacina</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>Forma de pagamento</td>
                    <td>
                        <select class="form-select" name="payment" required>
                            <option value="money" {% if servico.payment == 'banho' %}selected{% endif %}>Dinheiro</option>
                            <option value="card" {% if servico.payment == 'card' %}selected{% endif %}>Cartão de crédito</option>
                            <option value="bank-transfer" {% if servico.payment == 'bank-transfer' %}selected{% endif %}>Transferência bancária</option>
                            <option value="pix" {% if servico.payment == 'pix' %}selected{% endif %}>Pix</option>
                        </select>
                    </tr>		  
                 <tr>
                    <td colspan="2" align="center">
                        <button type="submit">Editar</button>
                    </td>
                </tr>
            
            </table>	
        </form>
    </div>
</section>
{% endblock %}

templates/servicos/listar_servicos.html
{% extends 'usuario/dashboard.html' %}
{% load static %}
{% block dash %}
<section #servico class="container servico_form" style="margin-top: 30px;">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <p style="color: red;">
                    {{ message }}
                </p>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <p style="color: green;">
                    {{ message }}
                </p>
            {% endif %}
        {% endfor %}
    {% endif %}

    <table style="width: 100%; border-collapse: collapse;">
        <tr>
            <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">ID</th>
            <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">Cliente</th>
            <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">Animal</th>
            <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">Tipo</th>
            <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;">Pagamento</th>
            <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;"></th>
            <th style="border: 1px solid #dddddd; text-align: left; padding: 8px;"></th>
        </tr>
        {% for servico in servicos %}
            <tr>
                <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">{{ servico.id }}</td>
                <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">{{ servico.client }}</td>
                <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">{{ servico.animal }}</td>
                <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">{{ servico.get_type_display }}</td>
                <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">{{ servico.get_payment_display }}</td>
                <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                    <a href="{% url 'editar-servico' servico.id %}" style="color: green; text-decoration: none;">Editar</a>
                </td>
                <td style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                    <a href="{% url 'apagar-servico' servico.id %}" style="color: red; text-decoration: none;">Apagar</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</section>
{% endblock %}